dist: trusty
sudo: false

cache:
  bundler: true

stages:
  - name: Build docs
    if: (type IN (push, pull_request)) OR branch = master

jobs:
  include:
    - stage: Build docs
      language: ruby
      rvm:
        - 2.6.5
      script:
        - gem install bundler:2.1.4
        - bundle exec middleman build --clean
