dist: trusty
sudo: false

# cache:
#   bundler: true

stages:
  - name: Build docs
    if: (type IN (push, pull_request)) OR branch = master

jobs:
  include:
    - stage: Build docs
      language: ruby
      rvm:
        - 2.6.5
      script:
        - gem install --no-document bundler "bundler:~>1.17" && bundle exec middleman build --clean
